/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Bar_Music_Player: typeof import('./src/components/player_bar/Bar_Music_Player.vue')['default']
    NBadge: typeof import('naive-ui')['NBadge']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDrawer: typeof import('naive-ui')['NDrawer']
    NDrawerContent: typeof import('naive-ui')['NDrawerContent']
    NFlex: typeof import('naive-ui')['NFlex']
    NGlobalStyle: typeof import('naive-ui')['NGlobalStyle']
    NLayout: typeof import('naive-ui')['NLayout']
    NLayoutSider: typeof import('naive-ui')['NLayoutSider']
    NMenu: typeof import('naive-ui')['NMenu']
    NMessageProvider: typeof import('naive-ui')['NMessageProvider']
    NSpace: typeof import('naive-ui')['NSpace']
    NTabPane: typeof import('naive-ui')['NTabPane']
    NTabs: typeof import('naive-ui')['NTabs']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Table_Edit_Tag: typeof import('./src/components/tag_list/table/Table_Edit_Tag.vue')['default']
    Table_Music_Effect: typeof import('./src/components/player_effect/table/Table_Music_Effect.vue')['default']
    Table_Music_PlayList_Line_Virtual: typeof import('./src/components/player_list/table/Table_Music_PlayList_Line_Virtual.vue')['default']
    Table_Updateing: typeof import('./src/components/update_list/table/Table_Updateing.vue')['default']
    View_Edit_Tag: typeof import('./src/components/tag_list/View_Edit_Tag.vue')['default']
    View_Player_Effect: typeof import('./src/components/player_effect/View_Player_Effect.vue')['default']
    View_Player_PlayList: typeof import('./src/components/player_list/View_Player_PlayList.vue')['default']
    View_Updateing: typeof import('./src/components/update_list/View_Updateing.vue')['default']
  }
}
