interface App_Configs_Props {
  theme: any,
  lang: any,
  router_name: string,
  app_left_menu_select_activeKey: string,
  app_left_menu_collapsed: any,
  model_select: any,
  server_select: any,
  username: any,
  password: any,
  play_order: any,
  play_volume: number,
  selectd_props_app_sidebar: string,
  model_server_type_of_web: any,
  model_server_type_of_local: any,
  authorization: string,
  client_unique_id: string,
  media_page_sizes: number,
  album_page_sizes: number,
  artist_page_sizes: number
};